<a href="https://colab.research.google.com/github/karthebans/Research/blob/main/RNN_Time_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
def generate_time_series(batch_size,n_steps):
    freq1, freq2, offset1, offset2, = np.random.rand(4,batch_size,1)
    time = np.linspace(0,1,n_steps)
    series = 0.5 * np.sin((time-offset1) * (freq1 * 10 + 10))
    series +=0.2 * np.sin((time - offset2) * (freq2 *20 + 20))
    series += 0.1 * (np.random.rand(batch_size, n_steps) - 0.5)
    return series[..., np.newaxis].astype(np.float32)

In [ ]:
n_steps = 50
series = generate_time_series(10000, n_steps= +1)
series

array([[[-0.10807878]],

       [[-0.36624837]],

       [[ 0.069507  ]],

       ...,

       [[ 0.2951545 ]],

       [[-0.24368274]],

       [[ 0.6137489 ]]], dtype=float32)

In [ ]:
series[0][0]

array([-0.10807878], dtype=float32)

In [ ]:
X_train, y_train = series[:7000, :n_steps], series[:7000, -1]

In [ ]:
X_train

array([[[-0.10807878]],

       [[-0.36624837]],

       [[ 0.069507  ]],

       ...,

       [[-0.5117974 ]],

       [[-0.3228529 ]],

       [[ 0.19405904]]], dtype=float32)

In [ ]:
y_train

array([[-0.10807878],
       [-0.36624837],
       [ 0.069507  ],
       ...,
       [-0.5117974 ],
       [-0.3228529 ],
       [ 0.19405904]], dtype=float32)

In [ ]:
x_valid, y_valid = series[7000:9000, :n_steps], series[7000:9000,-1]

In [ ]:
x_test, y_test = series[9000: , :n_steps], series[9000:,-1]

In [ ]:
x_test

In [ ]:
y_test

In [ ]:
import keras

In [ ]:
y_pred = x_valid[:,-1]

In [ ]:
y_pred

array([[-0.64195836],
       [-0.39677322],
       [-0.22487772],
       ...,
       [-0.09804105],
       [-0.1897724 ],
       [ 0.6668602 ]], dtype=float32)

In [ ]:
np.mean(keras.losses.mean_squared_error(y_valid,y_pred))

0.0

In [ ]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape = [50,1]),
    keras.layers.Dense(1)
])